let metroStation = [
    "Dilshad Garden",
    "Jhilmil",
    "Mansrover park",
    "Shahdara",
    "Welcome",
    "Seelam Pur",
    "Shastri Park",
    "Kashmere Gate",
    "Tis Hazari",
    "Pul Bangash",
    "Pratap Nagar",
    "Shastri Nagar",
    "Inderlok",
    "Kanhaiya Nagar",
    "Keshav Puram",
    "Netaji Subash Place",
    "Kohat Enclave",
    "Pitampura",
    "Rohini East",
    "Rohini West",
    "Rithala",
    "Mundka",
    "Rajdhani Park",
    "Nangloi Railway Station",
    "Nangloi",
    "Maharaja Surajmal Stadium",
    "Udyog Nagar",
    "Peera Garhi",
    "Paschim Vihar (West)",
    "Paschim Vihar (East)",
    "Madipur",
    "Shivaji Park",
    "Punjabi Bagh",
    "Ashok Park Main",
    "Satguru Ram Singh Marg",
    "Samaypur Badli",
    "Rohini Sector 18-19",
    "Haiderpur Badli Mor",
    "Jahangirpuri",
    "Adarsh Nagar",
    "Azadpur",
    "Model Town",
    "Guru Tegh Bahadur Nagar",
    "Vishwavidyalaya",
    "Vidhan Sabha",
    "Civil Lines",
    "Chandni Chowk",
    "Chawri Bazar",
    "New Delhi",
    "Rajiv Chowk",
    "Patel Chowk",
    "Central Secretariat",
    "Udyog Bhawan",
    "Lok Kalyan Marg",
    "Jorbagh",
    "Dilli Haat - INA",
    "AIIMS",
    "Green Park",
    "Hauz Khas",
    "Malviya Nagar",
    "Saket",
    "Qutab Minar",
    "Chhattarpur",
    "Sultanpur",
    "Ghitorni",
    "Arjan Garh",
    "Gurudronacharya",
    "Sikanderpur",
    "MG Road",
    "IFFCO Chowk",
    "Huda City Centre",
    "Vaishali",
    "Kaushambi",
    "Anand Vihar",
    "Karkarduma",
    "Preet Vihar",
    "Nirman Vihar",
    "Laxmi Nagar",
    "Noida City Centre",
    "Golf Course",
    "Botanical Garden",
    "Noida Sec -18",
    "Noida Sec -16",
    "Noida Sec -15",
    "New Ashok Nagar",
    "Mayur Vihar Ext",
    "Mayur Vihar-I",
    "Akshardham",
    "Yamuna Bank",
    "Indraprastha",
    "Supreme Court",
    "Mandi House",
    "Barakhamba",
    "RK Ashram Marg",
    "Jhandewalan",
    "Karol Bagh",
    "Rajendra Place",
    "Patel Nagar",
    "Shadipur",
    "Kirti Nagar",
    "Moti Nagar",
    "Ramesh Nagar",
    "Rajouri Garden",
    "Tagore Garden",
    "Subash Nagar",
    "Tilak Nagar",
    "Janak Puri East",
    "Janak Puri West",
    "Uttam Nagar East",
    "Uttam Nagar West",
    "Nawada",
    "Dwarka Mor",
    "Dwarka",
    "Dwarka Sector - 14",
    "Dwarka Sector - 13",
    "Dwarka Sector - 12",
    "Dwarka Sector - 11",
    "Dwarka Sector - 10",
    "Dwarka Sector - 9",
    "Dwarka Sector - 8",
    "Dwarka Sector - 21",
    "ITO",
    "Janpath",
    "Khan Market",
    "Jawahar Lal Nehru Stadium",
    "Jangpura",
    "Lajpat Nagar",
    "Moolchand",
    "Kailash Colony",
    "Nehru Place",
    "Kalkaji Mandir",
    "Govind Puri",
    "Harkesh Nagar Okhla",
    "Jasola-Apollo",
    "Sarita Vihar",
    "Mohan Estate",
    "Tughlakabad Station",
    "Badarpur Border",
    "Sarai",
    "NHPC Chowk",
    "Mewala Maharajpur",
    "Sector-28",
    "Badkal Mor",
    "Old Faridabad",
    "Neelam Chowk Ajronda",
    "Bata Chowk",
    "Escorts Mujesar",
    "Sikanderpur (Rapid Metro)",
    "Phase 2 (Rapid Metro)",
    "Belvedere Towers (Rapid Metro)",
    "Cyber City (Rapid Metro)",
    "Moulsari Avenue (Rapid Metro)",
    "Phase 3 (Rapid Metro)",
    "IGI Airport",
    "Delhi Aerocity",
    "Dhaula Kuan",
    "Shivaji Stadium",
    "Delhi Gate",
    "Jama Masjid",
    "Lal Quila",
    "Okhla Bird Sanctuary",
    "Kalindi Kunj",
    "Jasola Vihar Shaheen Bagh",
    "Okhla Vihar",
    "Jamia Millia Islamia",
    "Sukhdev Vihar",
    "Okhla NSIC",
    "Phase-I (Rapid Metro)",
    "Sector 42-43 (Rapid Metro)",
    "Sector 53-54 (Rapid Metro)",
    "Sector 54 Chowk (Rapid Metro)",
    "Sector 55-56 (Rapid Metro)",
    "Majlis Park",
    "Shalimar Bagh",
    "Shakurpur",
    "Punjabi Bagh West",
    "ESI Basai Darapur",
    "Mayapuri",
    "Naraina Vihar",
    "Delhi Cantt.",
    "Durgabai Deshmukh South Campus",
    "Nehru Enclave",
    "Greater Kailash",
    "Chirag Delhi",
    "Panchsheel Park",
    "IIT",
    "RK Puram",
    "Munirka",
    "Vasant Vihar",
    "Shankar Vihar",
    "Terminal 1- IGI Airport",
    "Sadar Bazar Contonment",
    "Palam",
    "Dashrath Puri",
    "Dabri Mor - Janakpuri South",
    "Mundka Industrial Area (M.I.A)",
    "Ghevra Metro station",
    "Tikri Kalan",
    "Tikri Border",
    "Pandit Shree Ram Sharma",
    "Bahadurgarh City",
    "Brigadier Hoshiyar Singh",
    "Sir Vishweshwaraiah Moti Bagh",
    "Bhikaji Cama Place",
    "Sarojini Nagar",
    "South Extension",
    "Trilokpuri Sanjay Lake",
    "East Vinod Nagar - Mayur Vihar-II",
    "Mandawali - West Vinod Nagar",
    "IP Extension",
    "Karkarduma Court",
    "Krishna Nagar",
    "East Azad Nagar",
    "Jafrabad",
    "Maujpur - Babarpur",
    "Gokulpuri",
    "Johri Enclave",
    "Shiv Vihar",
    "Sant Surdas (Sihi)",
    "Raja Nahar Singh",
    "Vinobapuri",
    "Ashram",
    "Sarai Kale Khan - Nizamuddin",
    "Mayur Vihar Pocket 1",
    "Shaheed Sthal (New Bus Adda)",
    "Hindon River",
    "Arthala",
    "Mohan Nagar",
    "Shyam Park",
    "Major Mohit Sharma Rajender Nagar",
    "Raj Bagh",
    "Shaheed Nagar",
    "Noida Sec-34",
    "Noida Sec-52",
    "Noida Sec-61",
    "Noida Sec-59",
    "Noida Sec-62",
    "Noida Electronic City",
    "Nangli",
    "Najafgarh",
    "Dhansa Bus Stand",
    "Noida Sector 51",
    "Noida Sector 50",
    "Noida Sector 76",
    "Noida Sector 101",
    "Noida Sector 81",
    "NSEZ",
    "Noida Sector 83",
    "Noida Sector 137",
    "Noida Sector 142",
    "Noida Sector 143",
    "Noida Sector 144",
    "Noida Sector 145",
    "Noida Sector 146",
    "Noida Sector 147",
    "Noida Sector 148",
    "Knowledge Park",
    "Pari Chowk",
    "Alpha 1",
    "Delta 1",
    "GNIDA Office",
    "Depot Station"
  ]

export { metroStation };